# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Linxcc_config = debug
  Test_config = debug
endif
ifeq ($(config),release)
  Linxcc_config = release
  Test_config = release
endif

PROJECTS := Linxcc Test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Linxcc:
ifneq (,$(Linxcc_config))
	@echo "==== Building Linxcc ($(Linxcc_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(Linxcc_config)
endif

Test:
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C linxc-out -f Makefile config=$(Test_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean
	@${MAKE} --no-print-directory -C linxc-out -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Linxcc"
	@echo "   Test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"