# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_windows
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_windows)
  Linxcc_config = debug_windows
endif
ifeq ($(config),debug_macos)
  Linxcc_config = debug_macos
endif
ifeq ($(config),debug_linux)
  Linxcc_config = debug_linux
endif
ifeq ($(config),release_windows)
  Linxcc_config = release_windows
endif
ifeq ($(config),release_macos)
  Linxcc_config = release_macos
endif
ifeq ($(config),release_linux)
  Linxcc_config = release_linux
endif

PROJECTS := Linxcc

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Linxcc:
ifneq (,$(Linxcc_config))
	@echo "==== Building Linxcc ($(Linxcc_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(Linxcc_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_windows"
	@echo "  debug_macos"
	@echo "  debug_linux"
	@echo "  release_windows"
	@echo "  release_macos"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Linxcc"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"